# Generated by Django 3.0.5 on 2020-05-17 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='full_link',
            field=models.CharField(default=None, max_length=65536, verbose_name='Исходная ссылка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='owner',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='short_link',
            field=models.CharField(default=None, max_length=64, verbose_name='Сокращенная ссылка'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=40, verbose_name='IP')),
                ('transition_date', models.DateTimeField(verbose_name='Дата и время перехода')),
                ('latitude', models.FloatField(null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(null=True, verbose_name='Долгота')),
                ('country', models.CharField(blank=True, max_length=64, verbose_name='Страна')),
                ('region', models.CharField(blank=True, max_length=128, verbose_name='Регион')),
                ('city', models.CharField(blank=True, max_length=128, verbose_name='Населенный пункт')),
                ('url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shortener.URL', verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Переход по ссылке',
                'verbose_name_plural': 'Переходы по ссылкам',
            },
        ),
    ]
