# Generated by Django 3.0.5 on 2020-05-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_url_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transition',
            name='transition_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время перехода'),
        ),
    ]
