# Generated by Django 3.0.5 on 2020-05-19 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_auto_20200519_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transition',
            old_name='transition_date',
            new_name='transition_datetime',
        ),
    ]
