# Generated by Django 3.0.5 on 2020-05-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0008_auto_20200519_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transition',
            name='ip',
            field=models.CharField(blank=True, max_length=40, verbose_name='IP'),
        ),
    ]
